import { describe, expect, it } from 'vitest';

import { normalizeFlatCookieString, parseCookieInputToFlat } from './cookie-parser';

describe('cookie parser compatibility', () => {
  it('detects Netscape format with header comments', () => {
    const input = [
      '# Netscape HTTP Cookie File',
      '# generated by browser extension',
      '.youtube.com	TRUE	/	FALSE	0	VISITOR_INFO1_LIVE	abc123',
    ].join('\n');

    const flat = parseCookieInputToFlat(input, 'youtube');
    expect(flat).toBe('VISITOR_INFO1_LIVE=abc123');
  });

  it('parses #HttpOnly_ Netscape cookie rows', () => {
    const input = '#HttpOnly_.facebook.com	TRUE	/	TRUE	0	c_user	10001';

    const flat = parseCookieInputToFlat(input, 'facebook');
    expect(flat).toBe('c_user=10001');
  });

  it('accepts JSON with uppercase keys and nested cookies array', () => {
    const input = JSON.stringify({
      Export: {
        Cookies: [
          { NAME: 'SID', VALUE: 'yt-session', DOMAIN: '.youtube.com' },
          { Name: 'HSID', Value: 'google-session', Domain: '.google.com' },
        ],
      },
    });

    const flat = parseCookieInputToFlat(input, 'youtube');
    expect(flat).toBe('SID=yt-session; HSID=google-session');
  });

  it('supports raw header string with Cookie: prefix', () => {
    const input = 'Cookie: c_user=1000; xs=abcd; fr=token';

    const flat = parseCookieInputToFlat(input, 'facebook');
    expect(flat).toBe('c_user=1000; xs=abcd; fr=token');
  });

  it('preserves duplicate cookie names in order', () => {
    const input = JSON.stringify([
      { name: 'SAPISID', value: 'first', domain: '.youtube.com' },
      { name: 'SAPISID', value: 'latest', domain: '.youtube.com' },
    ]);

    const flat = parseCookieInputToFlat(input, 'youtube');
    expect(flat).toBe('SAPISID=first; SAPISID=latest');
  });

  it('normalizes flat cookie string input', () => {
    const flat = normalizeFlatCookieString('a=1;  ; badchunk; b=2; a=3');
    expect(flat).toBe('a=1; b=2; a=3');
  });
});
