export {
  getResolvedLocale,
  getResolvedTheme,
  getSeasonalSettings,
  getTheme,
  getUnifiedSettings,
  getUpdateDismissed,
  initAccentColor,
  initTheme,
  loadBackgroundFromDB,
  saveTheme,
  setBackgroundEnabled,
  setBackgroundSound,
  setSeasonalMode,
  setUpdateDismissed,
  startRandomRotation,
  stopRandomRotation,
  type ResolvedTheme,
  type SeasonalSettings,
  type SeasonType,
  type ThemeType,
} from '@/infra/storage';
